### ISSUE TITLE
Show example of SQL equivalents in Readme

### ISSUE THREAD

**Issue by axelson** [kpanic/bombadil#1]
Hey, thanks for this project! I think it looks like it could be a very helpful tool for searching with Postgres.

I think one thing that would be helpful when reading the README is to show the SQL equivalent of every search.

**Comment by kpanic** [comment]
hey @axelson thanks!
Do you think that the PostgreSQL syntax would fit better than the one generated by ecto as prepared statements?

**Comment by axelson** [comment]
Yeah I think so. Would probably be easier to read

**Comment by kpanic** [comment]
@axelson I opened a PR #2 please have a look

**Comment by axelson** [comment]
Looks good to me :+1:

**Comment by kpanic** [comment]
Merged #2 closing this issue. Thank you! :+1:
